### ISSUE TITLE
Gocd installation fails on post-install scripts 

### ISSUE THREAD

**Issue by tomaszkrzyzanowski** [sansible/gocd_server#36]
Gocd installation fails on Ubuntu Xenial during post-installation scripts on default settings (when role is contained in playbook without additional parameter definition)

When version is changed to newest one (17.10.*) installation finish successfully 

Ansible version: 
```
ansible 2.4.0.0
  config file = /Users/tkrzyzanowski/.ansible.cfg
  configured module search path = ['/Users/tkrzyzanowski/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.2 (default, Jul 17 2017, 16:44:45) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```

Non working configuration:
``` yaml
---
- name: Install GO CD Server
  hosts: all

  roles:
    - name: sansible.gocd_server
```

Working configuration:
``` yaml
---
- name: Install GO CD Server
  hosts: all

  roles:
    - name: sansible.gocd_server
      gocd_server:
        version: "17.10.*"
```
